name: dynamic_storage_directory
description: "A Flutter package that provides a clean way to handle storage directory path on both web and non-web platforms and debug and release builds."
version: 1.0.0
homepage: https://github.com/ilCONDORA/dynamic_storage_directory

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

platforms:
  android:
  ios:
  windows:
  macos:
  linux:
  web:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
