name: condora_automatic_getter_storage_directory
description: "A Flutter package that provides an automatic and platform-aware solution for managing storage directories across web and non-web platforms, handling both debug and release environments efficiently."
version: 1.0.0
homepage: https://github.com/ilCONDORA/condora_automatic_getter_storage_directory

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

platforms:
  android:
  ios:
  windows:
  macos:
  linux:
  web:

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
